// <auto-generated />
namespace BankApiApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AccountAccountTransactionadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccountAccountTransactionadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201810121048323_AccountAccountTransactionadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
