CREATE TABLE FOO(
id INT IDENTITY(1,1),
description VARCHAR(10) NOT NULL
);
INSERT INTO FOO(description) VALUES('FIRST');
SELECT * FROM FOO

BEGIN TRANSACTION
INSERT INTO FOO(description) VALUES('THREE')
SELECT * FROM FOO
ROLLBACK 

BEGIN TRANSACTION
PRINT @@TRANCOUNT
BEGIN TRY
	PRINT @@TRANCOUNT
	INSERT INTO FOO(description) VALUES('five')
	INSERT INTO FOO(description) VALUES('six'+5)
	COMMIT
	PRINT @@TRANCOUNT
	PRINT 'SUCCESSFULLY INSERTED ALL DATA..'
END TRY
BEGIN CATCH
PRINT @@TRANCOUNT
IF @@TRANCOUNT>0
PRINT 'INSIDE IF BLOCK'
ROLLBACK
PRINT @@TRANCOUNT
PRINT 'ERROR IN INSERT  QUERY..'
END CATCH







